### ISSUE TITLE
db not proper

### ISSUE THREAD

**Issue by meghakundu** [iceburgcrm/iceburgcrm#19]
tables missing or their fields too. dashboard not opening @iceburgcrm

**Comment by iceburgcrm** [comment]
What command are you using to seed the database?

**Comment by meghakundu** [comment]
> What command are you using to seed the database?

"php artisan db:seed". tables such as "lineitems"missing comes after login as admin in dashboard

**Comment by meghakundu** [comment]
> We've changed how to seed in the latest versions.
> 
> Please try this custom command: php artisan iceburg:seed

ok,thanks. Will go ahead with this!

**Comment by iceburgcrm** [comment]
Try again with the latest release using artian iceburg:create
