### ISSUE TITLE
Integrity constraint violation error when adding new user

### ISSUE THREAD

**Issue by thinkverse** [iceburgcrm/iceburgcrm#3]
Iceburg CRM doesn't allow an administrator to add a new user since it doesn't have a `password` field. I added one manually, but the profile picture isn't sent in the request, causing an integrity constraint violation error.

### Request sent to server.

![Network request without the profile picture](https://user-images.githubusercontent.com/2221746/213925270-c207e491-b0da-4eae-8f1a-8b127d699fac.png)

### Integrity constraint violation.

![Network response with SQL error](https://user-images.githubusercontent.com/2221746/213925284-f20e869f-01f4-4051-a89c-740f8d7f4573.png)

Also tried with adding back the `register` routes, but that doesn't have a profile picture input, causing the same integrity constraint violation error.

**Comment by iceburgcrm** [comment]
This is resolved in the new version 1.7.5
