### ISSUE TITLE
No permissions created for new module

### ISSUE THREAD

**Issue by thinkverse** [iceburgcrm/iceburgcrm#4]
I created a module via the builder and noticed that no permissions were created for it, so I cannot access the new module even though it was created, all the fields are in the database, and the module's database was created as well.

And I cannot seems to find a way to manually add permissions in the panel either. 🤔

**Comment by iceburgcrm** [comment]
Did you generate the module after you created it?

**Comment by thinkverse** [comment]
Yes, the database and field columns was generated. And looking at the code for the `CRMBuilder` and the `generate` method for `Module` I don't see it creating or calling anything that generate permissions. 🤷‍♂️ Could be missing it being tired though.

**Comment by iceburgcrm** [comment]
That's been fixed in v1.8.5

The admin role is granted permission now.
